### ISSUE TITLE
test data **must** not be in NuGridPy project repo

### ISSUE THREAD

**Issue by 2sn** [NuGrid/NuGridPy#6] opened 2016-06-08 21:08 UTC
# Do not put test data in NuGridPy Repo

@adam-paul @fherwig 
I just found Adam's new branch/commit `regression-tests` https://github.com/NuGrid/NuGridPy/commit/b836e7d73750ba06cc8f0e4e57657321701591bb

As we discussed, test data **must not be but in `NuGridPy` repo**
As I said in my post to #5 , we should have a **separate** repo for test data.
Now these huge data files will be part of the `NuGridPy` repo for ever - and be downloaded by everyone all the time?
@adam-paul , could you please clean this?
Test data should definitively not be in this repo!

**Comment by 2sn** [comment] 2016-06-08 21:14
@adam-paul 
maybe the current `regression-tests` branch can just be deleted?
Then a new branch w/o data can be made, and a new NuGrid repo with test data be made from which the files are read?  Instructions may state where the files should be located or open file dialog box.

**Comment by 2sn** [comment] 2016-06-08 21:21
@adam-paul 
for your tests, you should not just put code at the package level, but create test functions, better classes, instead, that are being called.  _Be organised_
Could you please refactor this?  in `regression-tests/abu_chart.py` I updated relative imports as an example.

**Comment by adam-paul** [comment] 2016-06-08 21:25
@2sn 

That's fine, it is not intended to live here -- only pushed temporarily to provide some data for testing these bugs. I agree that a new repo or different home for test data is necessary. 

These examples and test data are actually already living in the NuPPN repository in the examples -- I have simply started refactoring them for regression tests, but yes they do indeed need a lot of work still! I will remove the branch for now.

**Comment by 2sn** [comment] 2016-06-08 21:35
@ I tried to merge your branch with my fix branch but somehow, e.g., in utils.pt the resulting relative imports present in my branch are not presnet in yours

``` shell
[py3fix_alex] ~/NuGrid/NuGridPy>head -n 25 utils.py
'''
utils.py

Utility class for holding extra methods from mesa.py, nuh5p.py

'''
from __future__ import division
from __future__ import print_function
from __future__ import absolute_import

from builtins import zip
from builtins import str
from builtins import range
from past.utils import old_div
from builtins import object

import numpy as np
import scipy as sc
from . import ascii_table as att

from scipy import optimize
import matplotlib.pyplot as pl
import os

class data_fitting(object):

[py3fix_alex] ~/NuGrid/NuGridPy>git checkout regression-tests 
Switched to branch 'regression-tests'
Your branch is up-to-date with 'origin/regression-tests'.
[regression-tests] ~/NuGrid/NuGridPy>head -n 25 utils.py
'''
utils.py

Utility class for holding extra methods from mesa.py, nuh5p.py

'''
from __future__ import division
from __future__ import print_function
from __future__ import absolute_import

from builtins import zip
from builtins import str
from builtins import range
from past.utils import old_div
from builtins import object

import numpy as np
import scipy as sc
import ascii_table as att

from scipy import optimize
import matplotlib.pyplot as pl
import os

class data_fitting(object):
```

**Comment by 2sn** [comment] 2016-06-08 21:41
@adam-paul @fherwig @korobkin 
The point is that you **must** not put temporary huge data files in the git repo as git keeps all history.
Could you please kill this branch and make a new one with just the test routines.
Maybe best base on a new checkout of the fix branch, something in your current branch is not right, it does not contain the relative imports.  Not sure how you did that ...

Please make a separate repo for test data.

**Comment by 2sn** [comment] 2016-06-08 21:56
@adam-paul @fherwig 
also, as a suggestion for work flow and test package design - this should be exactly the same way as the users see it.  So do not check out NuGridPy as nugriddev for the test code; it should always be checked out with default paths and the test routines to use these.  What you _can_ do instead is to use virtual environments - e.g., https://docs.python.org/3.5/library/venv.html or the python2 equivalent.

**Comment by korobkin** [comment] 2016-06-09 00:10
@2sn @adam-paul @fherwig Just found this conversation. I agree with Alex: test data shouldn't be under git control. It has to either be created by test cases on-the-fly, or downloaded from some remote location.
Also, it is interesting how jupyter notebooks don't mesh very well with git: even without output, as soon as launched they become overwritten with user-specific information, such as number of executions, python version etc. Perhaps we shouldn't use jupyter notebooks for any testing.

**Comment by fherwig** [comment] 2016-06-13 20:29
OK @adam-paul @2sn @korobkin 

this turns into a discussion forum. We agree:
- do not put test data on git!!
- instead we can use wget to pull individual files from the CADC VOspace

Are there any other actionable items? Otherwise I want to close this issue.

**Comment by adam-paul** [comment] 2016-06-15 00:28
Agreed. There is currently still test data on the repo, but only a few files. Should these be removed (i.e. the regression-tests branch killed again) so they don't proliferate further? 

As for `wget` vs. a test data repo. My vote is for `wget` only because linking the regression tests to another github repo the way we are now (currently on the `unittest` branch the test data is coming from the NuPPN directory) seems ripe for error if someone just pulls the NuGridPy release and doesn't have a NuPPN directory. With `wget` we could simply issue a warning when no test data is found that tells the user how to `wget` some test data.

**Comment by 2sn** [comment] 2016-06-15 01:33
@adam-paul CC @korobkin @fherwig 
yes, please kill the branch with the test data in github.  People who did a fetch with this branch in it need to delete the directory and checkout fresh or `git gc` garbage collect after a new fetch.
It may be useful to create a temp directory (using python temporary file utilities) so test data can be cached?

**Comment by adam-paul** [comment] 2016-06-24 18:24
@2sn @fherwig @korobkin 

The test data has been removed from the repository, and the `tempfile` framework that @2sn showed us is now in place for the regression tests, with test data coming from the CADC VOspace into a temporary directory through a `wget` command. 

Should we close this issue now, or leave it open for future discussion if new approaches are desired/suggested?

**Closed as completed** 2016-07-08 05:42 UTC
Labels: enhancement
