### ISSUE TITLE
get method not working ANYMORE in ppn module after python3 branch merge

### ISSUE THREAD

**Issue by fherwig** [NuGrid/NuGridPy#8] opened 2016-06-11 00:01 UTC
@korobkin @2sn 

We @OClarkson @adam-paul etc have started to test the new master (should have done that before the merge!!!) and ran immediately into an issue. Cannot execute abu_chart plot. Using python 2 anaconda from [Nubuntu16 VM](https://github.com/NuGrid/NuGridDoc/blob/master/Resources/nubuntu16.md) 
and on [plone](http://www.nugridstars.org/data-and-software/virtual-box-releases/copy_of_readme/) as reference platform. The problem can be traced to failure of the get method.

You can `wget` [the test data file](http://uvic.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/transfer/bmVpZ2g9VVZJQyZzaWdleHA9MjAxNjA2MTEwMzU3MTEmYXJjPVZPU3BhYyZpZD0yMzExMDY1MTEmdXNlcj1maGVyd2lnJm5zPW51Z3JpZCUyRmRhdGElMkZwcm9qZWN0cyUyRnBwbiUyRmV4YW1wbGVzJTJGcHBuX0hidXJuX3NpbXBsZSZtZXRoPWdldCZhdXRoQ29kZT0wJnJ1bklEPXhxbTlkMWxwamNkemsyeWomdXJsPWh0dHAlM0ElMkYlMkZhZGNhY2hlMjElM0E4ODg4JTJGY2FjaGUlMkY0MDJjNTYyMCUyRjEzMzUlMkZ2b3NwYWMlMkZkZWZhdWx0JTJGMDAlMkYwMSUyRjgyJTJGMjMxMTA2NTExJTI1M0IlMjUzQjI0Mzc5OTQwNiZ1cmw9aHR0cCUzQSUyRiUyRmFkY2FjaGUyMiUzQTg4ODglMkZjYWNoZSUyRjI0ODk2YjhkJTJGMTMzNSUyRnZvc3BhYyUyRmRlZmF1bHQlMkYwMCUyRjAxJTJGODIlMkYyMzExMDY1MTElMjUzQiUyNTNCMjQzNzk5NDA2-ZmlkPWlzb19tYXNzZjAwMDIzLkRBVCZjbG49MjQzNyZjbWQ9ODBlZmRkMThlNzE1NzMzOTU4MDk3Yzg3MTg0MzhhODcmbG1kPTE0NjU1ODY3NjM0MTc=-c17af65e918ab27907bb877fe87d72f7/iso_massf00023.DAT) from the CADC VOspace.

![screen shot 2016-06-10 at 4 51 55 pm](https://cloud.githubusercontent.com/assets/10589734/15981537/bc3eb436-2f2b-11e6-9f18-6b4c1cebe98e.png)

In the above `pold` and `aold` refer to the NuGridPy pip package module, i.e the good old stuff ....

This is a bug that makes NuGridPy on the repo unusable.

**Comment by korobkin** [comment] 2016-06-11 00:14
@fherwig Strange, I cannot reproduce this bug:
![screenshot from 2016-06-10 18 11 12](https://cloud.githubusercontent.com/assets/389823/15981738/2c657992-2f37-11e6-93d5-f3e5a1783755.png)

**Comment by korobkin** [comment] 2016-06-11 00:25
@fherwig Sorry I was on the unittest branch. This bug should be fixed after the merge: #9

**Comment by 2sn** [comment] 2016-06-11 04:10
At DXB airport 
@fherwig 
I do not understand your code.
For quoting, could you please inline the examples as code using triple quotes rather than pasting a figure?
The line 

``` python
import ppn as pold
```

Does not seem to import anything from the new NuGridPy, in contrast to the first line.

**Comment by 2sn** [comment] 2016-06-11 04:19
@fherwig 
I cannot get the test data.  It says "unauthorized".  Can this be put on a more accessible place.

**Comment by fherwig** [comment] 2016-06-11 17:29
@2sn Forgot to open the permissions, try now, this link should work: 

http://uvic.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/transfer/bmVpZ2g9VVZJQyZzaWdleHA9MjAxNjA2MTEyMTI2NDYmYXJjPVZPU3BhYyZpZD0yMzExMDY1MTEmdXNlcj1hbm9uVXNlciZucz1udWdyaWQlMkZkYXRhJTJGcHJvamVjdHMlMkZwcG4lMkZleGFtcGxlcyUyRnBwbl9IYnVybl9zaW1wbGUmbWV0aD1nZXQmYXV0aENvZGU9MCZydW5JRD1oNzJvZTFpbjhob2x5a3ZyJnVybD1odHRwJTNBJTJGJTJGYWRjYWNoZTIxJTNBODg4OCUyRmNhY2hlJTJGNDAyYzU2MjAlMkYxMzM1JTJGdm9zcGFjJTJGZGVmYXVsdCUyRjAwJTJGMDElMkY4MiUyRjIzMTEwNjUxMSUyNTNCJTI1M0IyNDM3OTk0MDYmdXJsPWh0dHAlM0ElMkYlMkZhZGNhY2hlMjIlM0E4ODg4JTJGY2FjaGUlMkYyNDg5NmI4ZCUyRjEzMzUlMkZ2b3NwYWMlMkZkZWZhdWx0JTJGMDAlMkYwMSUyRjgyJTJGMjMxMTA2NTExJTI1M0IlMjUzQjI0Mzc5OTQwNg==-ZmlkPWlzb19tYXNzZjAwMDIzLkRBVCZjbG49MjQzNyZjbWQ9ODBlZmRkMThlNzE1NzMzOTU4MDk3Yzg3MTg0MzhhODcmbG1kPTE0NjU2NjU5OTE5NTM=-05db88bbedf64840203b69a2c1c0535c/iso_massf00023.DAT

This is one file in a full ppn example output: http://www.canfar.phys.uvic.ca/vosui/#/nugrid/data/projects/ppn/examples/ppn_Hburn_simple

@korobkin we tested with anaconda python 2. You can try the Nubuntu16 VM as a reference platform.

**Comment by fherwig** [comment] 2016-06-11 20:53
@2sn 

> At DXB airport 
> @fherwig 
> I do not understand your code.
> For quoting, could you please inline the examples as code using triple quotes rather than pasting a figure?
> The line
> 
> import ppn as pold
> Does not seem to import anything from the new NuGridPy, in contrast to the first line.

This was a demonstration: old is the instance from the NuGridPy pip package installed on the system, showing what should be the right response.

**Comment by 2sn** [comment] 2016-06-12 05:31
@fherwig @korobkin 
One downside of your test that may (or may not) cause the problem in the first place is that you still have all the old utils installed in the path and those may interfere with the new package.  You need to test the new package in a session/installation/machine w/o the old packages installed.  Oleg writes he cannot reproduce your bug - maybe this is why - I can only test whether it works in a current python3 install, maybe a standard python two install, but you need a "clean" test environment as well.  Could you please try that?

**Comment by korobkin** [comment] 2016-06-12 09:12
@2sn @fherwig I was able to reproduce it after all. Now it should be fixed in master. See #9 : there was a problem with using "isinstance", which for simple strings and integers becomes something really complicated when used with `future`.
Current branch `master` should be fine with respect to this bug.

**Comment by 2sn** [comment] 2016-06-12 16:07
fixed by #9

**Closed as completed by 2sn** 2016-06-12 16:07 UTC
Labels: bug
