### ISSUE TITLE
nugridse.abuprofile plots only partially in python 3

### ISSUE THREAD

**Issue by fherwig** [NuGrid/NuGridPy#40] opened 2017-11-08 03:47 UTC
This example code:
```
%pylab
data_dir='/data/nugrid_apod2/'
from nugridpy import nugridse as mp
mp.set_nugrid_path(data_dir)
ppd=mp.se(mass=2,Z=0.001)
ppd.abu_profile(fname=ppd.se.cycles[-1],isos=['C-12','O-16'],logy=True)
```
will produce a partial plot in python 3 but works in python 2. 

Task: fix nugridse so that plot works the same in python 3 as in python 2.

**Comment by jerichooconnell** [comment] 2017-11-09 18:38
Same as issue #38. This is caused by the utils.linestyle returning an int64 for the markevery parameter. It is fixed in the current version just not on the one in astrohub.

**Closed as completed** 2017-11-14 03:46 UTC
